#!/bin/sh

printf "\n"
# set foreground color to blue
printf "\033[0;34m"
printf "        ╔═╗╔═╗╦ ╦\n"
printf "        ╠═╝║  ║║║\n"
printf "        ╩  ╚═╝╚╩╝\n"
# set foreground color to white
printf "\033[0;37m"
printf "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n"
# set foreground color to blue
printf "\033[0;34m"
printf "Provenant Command-Line Wallet\n"
# set foreground color to gray
printf "\033[0;37m"
